services:
  # Backend (Flask + Telegram Bot)
  - type: web
    name: ai-bot-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
